sudo: required
language: python
services:
  - docker
env:
  global:
    - DOCKER_REPO=order-backend-rust
    - EB_REGION="ap-northeast-2"
    - AWS_ACCOUNT_ID: 410450153592
    - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws configure set default.region ${EB_REGION}
  - $(aws ecr get-login --no-include-email)

  - ls -al
  - mkdir -p zip
  - cd zip

  - cp -r ../scripts ./
  - cp -r ../appspec.yml ./
  - cp -r  ../env-example ./.env
  - zip -r api.zip . # node-koa-server 라는 이름으로 zip 파일 생성
  - ls -al
  - cd ../
  - mkdir -p deploy # deploy 라는 디렉터리를 만듬
  - mv zip/api.zip deploy/api.zip

script:
  - docker build -f "cargo-run.Dockerfile" -t order-backend-rust:latest .
deploy:
  - provider: script
    script: bash docker_push.sh

  