sudo: required
language: python
services:
  - docker
env:
  global:
    - DOCKER_REPO=order-backend-rust
    - EB_REGION="ap-northeast-2"
    - AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
    - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
before_install:
  - pip install awscli
  - export PATH=$PATH:$HOME/.local/bin
script:
  - docker build -f "cargo-run.Dockerfile" -t $DOCKER_REPO:latest .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master