version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/api
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/docker-run.sh
      runas: root
  AfterInstall:
    - location: scripts/blue-green.sh
      runas: root
