version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy-image
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/deploy-before-install.sh
      runas: root
  AfterInstall:
    - location: scripts/deploy-after-install.sh
      runas: root
